# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb/predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pb/predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pb/predict.proto\x12\x07predict\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2G\n\tPredictor\x12:\n\x07Predict\x12\x15.predict.ImageRequest\x1a\x18.predict.PredictResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_IMAGEREQUEST']._serialized_start=29
  _globals['_IMAGEREQUEST']._serialized_end=63
  _globals['_PREDICTRESPONSE']._serialized_start=65
  _globals['_PREDICTRESPONSE']._serialized_end=98
  _globals['_PREDICTOR']._serialized_start=100
  _globals['_PREDICTOR']._serialized_end=171
# @@protoc_insertion_point(module_scope)
