// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: pb/predict.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// リクエストメッセージ
type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // ここにGoで受け取ったバイナリをそのまま詰め込みます
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_pb_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_pb_predict_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

// レスポンスメッセージ
type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // 推論された文字列（文字）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_pb_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_pb_predict_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_pb_predict_proto protoreflect.FileDescriptor

const file_pb_predict_proto_rawDesc = "" +
	"\n" +
	"\x10pb/predict.proto\x12\apredict\"-\n" +
	"\fImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\")\n" +
	"\x0fPredictResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2G\n" +
	"\tPredictor\x12:\n" +
	"\aPredict\x12\x15.predict.ImageRequest\x1a\x18.predict.PredictResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_predict_proto_rawDescOnce sync.Once
	file_pb_predict_proto_rawDescData []byte
)

func file_pb_predict_proto_rawDescGZIP() []byte {
	file_pb_predict_proto_rawDescOnce.Do(func() {
		file_pb_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_predict_proto_rawDesc), len(file_pb_predict_proto_rawDesc)))
	})
	return file_pb_predict_proto_rawDescData
}

var file_pb_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_predict_proto_goTypes = []any{
	(*ImageRequest)(nil),    // 0: predict.ImageRequest
	(*PredictResponse)(nil), // 1: predict.PredictResponse
}
var file_pb_predict_proto_depIdxs = []int32{
	0, // 0: predict.Predictor.Predict:input_type -> predict.ImageRequest
	1, // 1: predict.Predictor.Predict:output_type -> predict.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_predict_proto_init() }
func file_pb_predict_proto_init() {
	if File_pb_predict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_predict_proto_rawDesc), len(file_pb_predict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_predict_proto_goTypes,
		DependencyIndexes: file_pb_predict_proto_depIdxs,
		MessageInfos:      file_pb_predict_proto_msgTypes,
	}.Build()
	File_pb_predict_proto = out.File
	file_pb_predict_proto_goTypes = nil
	file_pb_predict_proto_depIdxs = nil
}
